version: "3"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: booksdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
